export const toneCategories = {
  'Tons emotionnels': {
    Positifs: [
      'inspirant',
      'passionne',
      'enthousiaste',
      'optimiste',
      'empathique',
      'bienveillant',
      'reconnaissant',
      'reconfortant',
      'nostalgique',
      'reveur',
    ],
    'Negatifs ou complexes': [
      'sarcastique',
      'ironique',
      'cynique',
      'critique',
      'polemique',
      'alarmiste',
      'indigne',
      'dramatique',
    ],
  },
  'Tons professionnels et corporate': {
    Tons: [
      'formel',
      'institutionnel',
      'expert',
      'pedagogique',
      'confiant',
      'direct',
      'rassurant',
      'visionnaire',
      'transparent',
      'conciliant',
      'professionnel',
    ],
  },
  'Tons creatifs et originaux': {
    Tons: [
      'spirituel',
      'poetique',
      'decale',
      'minimaliste',
      'ludique',
      'mysterieux',
      'elegant',
      'surrealiste',
      'creatif',
      'artistique',
      'imaginatif',
    ],
  },
  'Tons persuasifs': {
    Tons: [
      'convaincant',
      'urgent',
      'engage',
      'autoritaire',
      'exclusif',
      'incitant',
      'vendeur',
      'charismatique',
      'influent',
      'seducteur',
      'provocant',
      'persuasif',
      'motivationnel',
      'promotionnel',
    ],
  },
  'Tons factuels et reflechis': {
    Tons: [
      'analytique',
      'objectif',
      'detache',
      'pragmatique',
      'curieux',
      'sceptique',
      'reflechi',
      'informatif',
      'educatif',
      'technique',
      'scientifique',
      'journalistique',
    ],
  },
  'Tons decontractes': {
    Tons: [
      'conversationnel',
      'authentique',
      'spontane',
      'humble',
      'taquin',
      'decontracte',
      'amical',
      'humoristique',
      'leger',
    ],
  },
};

export const allTones = Object.values(toneCategories)
  .flatMap((groups) => Object.values(groups).flat())
  .filter((tone, index, tones) => tones.indexOf(tone) === index);
